config/routes.rb
Bloodycms::Application.routes.draw do
  resources :sponsors, :path => Settings.get("sponsors:path", "sponsors") if Settings.get('sponsors:enabled?')
  match "/sponsors/image/:size/:id.png" => "sponsors#image" if Settings.get('sponsors:enabled?')
  resources :events,  :path => Settings.get("events:path", "events") if Settings.get('events:enabled?')
  resources :posts, :path => Settings.get("blog:path", "blog") if Settings.get('blog:enabled?')
  resources :pages, :except => :index
  resources :authentications
  resources :admins
  
  match "/options" => "options#index", :as => "options"  
  
  #authentication
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/twitter/setup', :to => 'authentications#setup'
  match '/auth/failure' => redirect("/")
  match '/login' => redirect('/auth/twitter'), :as => "login"
  match '/logout' => "authentications#destroy", :as => "logout"
  
  
  #pages to root domain
  match "/:id" => "pages#show", :as => "root_page", :method => :get

  #the root url can be configured
  root :to => 'frontpage#index'
end

app/models/sponsor.rb
require 'url_validator'

class Sponsor < ActiveRecord::Base
  attr_accessible :name, :description, :url, :image
  
  before_validation :slugify

  validates_presence_of :name, :description, :url
  validates_uniqueness_of :slug, :message => "^A sponsor with a similar title already exists"
  validates :url, :url => true, :allow_blank => true
  validates :image, :url => true, :allow_blank => true

  scope :by_name, order("name ASC")
  
  def to_param
    "#{slug}"
  end
  
  def image_for_size(size)
    "/sponsors/image/#{size}/#{self.slug}.png"
  end
  
  private
  
  def slugify
    self.slug = self.name.parameterize
  end
end

app/controllers/sponsors_controller.rb
require "mini_magick"

class SponsorsController < ApplicationController
  # GET /sponsors
  # GET /sponsors.json
  def index
    @sponsors = Sponsor.by_name

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sponsors }
    end
  end

  # GET /sponsors/1
  # GET /sponsors/1.json
  def show
    @sponsor = Sponsor.find_by_slug(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sponsor }
    end
  end

  # GET /sponsors/new
  # GET /sponsors/new.json
  def new
    @sponsor = Sponsor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sponsor }
    end
  end

  # GET /sponsors/1/edit
  def edit
    @sponsor = Sponsor.find_by_slug(params[:id])
  end

  # POST /sponsors
  # POST /sponsors.json
  def create
    @sponsor = Sponsor.new(params[:sponsor])

    respond_to do |format|
      if @sponsor.save
        format.html { redirect_to @sponsor, notice: 'Sponsor was successfully created.' }
        format.json { render json: @sponsor, status: :created, location: @sponsor }
      else
        format.html { render action: "new" }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sponsors/1
  # PUT /sponsors/1.json
  def update
    @sponsor = Sponsor.find_by_slug(params[:id])

    respond_to do |format|
      if @sponsor.update_attributes(params[:sponsor])
        format.html { redirect_to @sponsor, notice: 'Sponsor was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sponsors/1
  # DELETE /sponsors/1.json
  def destroy
    @sponsor = Sponsor.find_by_slug(params[:id])
    @sponsor.destroy

    respond_to do |format|
      format.html { redirect_to sponsors_url }
      format.json { head :ok }
    end
  end
  
  def image 
    @sponsor = Sponsor.find_by_slug(params[:id])
     
    image = MiniMagick::Image.open(@sponsor.image)
    image.resize params[:size]
    image.format "png"
    
    logger.info "Resizing happened!"
    
    headers['Cache-Control'] = 'public; max-age=2592000'
    
    send_data image.to_blob, :disposition => 'inline', :type => "image/png"
  end
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/views/sponsors/_form.html.erb
<%= form_for(@sponsor) do |f| %>
  <% if @sponsor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sponsor.errors.count, "error") %> prohibited this sponsor from being saved:</h2>

      <ul>
      <% @sponsor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name, :placeholder => "Name" %>
  </div>
  <div class="field">
	  <%= render :partial => 'markdown_info' %><br/>
    <%= f.text_area :description, :placeholder => "Sponsor description..." %>
  </div>
	<hr/>
  <div class="field">
    <%= f.label :url, "Sponsor URL" %>
    <%= f.text_field :url, :placeholder => "http://" %>
  </div>
  <div class="field">
    <%= f.label :image, "Sponsor image URL" %>
		<span class='info'>
		  URL for a large image of the sponsor. Will be automatically resized to be used on pages and in the sidebar.
		</span>
    <%= f.text_field :image, :placeholder => "http://" %>
  </div>
	<hr/>
  <div class="controls">
		<% unless @sponsor.new_record? %>
	  	<%= link_to '&larr;	Back'.html_safe, @sponsor, :class => "button medium white left" %>
	  	<%= link_to 'Delete', @sponsor, confirm: 'Are you sure?', method: :delete, :class => 'button gray medium left' %>
		<% else %>
			<%= link_to '&larr;	Back'.html_safe, sponsors_url, :class => "button medium white left" %>
		<% end %>

		<% if @sponsor.new_record? %>
			<%= f.submit(:class => 'button medium green', :value => 'Create sponsor') %>
		<% else %>
			<%= f.submit(:class => 'button medium green', :value => 'Update sponsor') %>
		<% end %>
  </div>
<% end %>

app/views/sponsors/_sponsor.html.erb
<% sponsor ||= @sponsor %>

<article>
	<header>
		<%= link_to sponsor.name, sponsor %>
		<%= link_to sponsor.url, sponsor.url, :class => 'light' %>
	</header>
	
	<%= link_to image_tag(sponsor.image_for_size("600x100")), sponsor.url unless sponsor.image.blank?  %>
	
	<div><%= markdown(sponsor.description) %></div>
	
	<%= render :partial => "sponsors/sponsor_controls", :locals => {:sponsor => sponsor} if show_nav && admin? %>
  
</article>

app/views/sponsors/_sponsor_controls.html.erb
<% sponsor ||= @sponsor %>

<div class='controls'>	
	<%= link_to '&larr;	Back'.html_safe, sponsors_path, :class => 'button white medium left' unless root? || request.url == sponsors_url %>
	<%= link_to 'Edit', edit_sponsor_path(sponsor), :class => 'button orange medium' %>
</div>

app/views/sponsors/edit.html.erb
<section>
	<header>Editing sponsor</header>

	<%= render 'form' %>
</section>

app/views/sponsors/index.html.erb
<section>
	<header><%= Settings.get("sponsors:title") %></header>
  <% if admin? %>
		<div class="controls">
			<%= link_to 'Add a Sponsor', new_sponsor_path, :class => "button medium green" %>
		</div>
	<% end %>
	
	<% @sponsors.each do |sponsor| %>
		<%= render :partial => sponsor, :locals => {:show_nav => true} %>
	<% end %>


</section>

app/views/sponsors/new.html.erb
<section>
	<header>New sponsor</header>

	<%= render 'form' %>
</section>

app/views/sponsors/show.html.erb
<% content_for :title do %>
	<%= "#{@sponsor.name} | " unless root? %>
<% end %>

<section>
	<%= render :partial => @sponsor, :locals => {:show_nav => true} %>
</section>