config/routes.rb
Bloodycms::Application.routes.draw do
  resources :sponsors, :path => Settings.get("sponsors:path", "sponsors") if Settings.get('sponsors:enabled?')
  match "/sponsors/image/:size/:id.png" => "sponsors#image" if Settings.get('sponsors:enabled?')
  resources :events,  :path => Settings.get("events:path", "events") if Settings.get('events:enabled?')
  resources :posts, :path => Settings.get("blog:path", "blog") if Settings.get('blog:enabled?')
  resources :pages, :except => :index
  resources :authentications
  resources :admins
  
  match "/options" => "options#index", :as => "options"  
  
  #authentication
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/twitter/setup', :to => 'authentications#setup'
  match '/auth/failure' => redirect("/")
  match '/login' => redirect('/auth/twitter'), :as => "login"
  match '/logout' => "authentications#destroy", :as => "logout"
  
  
  #pages to root domain
  match "/:id" => "pages#show", :as => "root_page", :method => :get

  #the root url can be configured
  root :to => 'frontpage#index'
end

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title, :placeholder => "Title" %>
  </div>
	<hr/>
	<%= render :partial => 'markdown_info' %>
	<div class="field">
    <%= f.text_area :content, :placeholder => 'Content' %>
  </div>
	<div class="field">
    <%= f.text_field :sidebar_title, :placeholder => 'Custom sidebar title' %>
  </div>
	<hr/>
	<div class="field">
    <%= f.check_box :show_in_sidebar %> <%= f.label :show_in_sidebar, "Show this page in the sidebar", :class => 'inline' %>
  </div>
	<hr/>
  <div class="controls">
	  <%= link_to '&larr;	Back'.html_safe, root_page_path(@page), :class => "button medium white left" unless @page.new_record? %>
	  <%= link_to '&larr;	Back'.html_safe, root_url, :class => "button medium white left" if @page.new_record? %>
	  <%= link_to 'Delete', @page, confirm: 'Are you sure?', method: :delete, :class => 'button gray medium left' unless @page.new_record? %>

		<% if @page.new_record? %>
			<%= f.submit(:class => 'button medium green', :value => 'Save page') %>
			<%= f.submit(:class => 'button medium orange', :value => 'Publish') %>
		<% elsif !@page.published? %>
			<%= f.submit(:class => 'button medium green', :value => 'Update page') %>
			<%= f.submit(:class => 'button medium orange', :value => 'Publish') %>
		<% else %>
			<%= f.submit(:class => 'button medium orange', :value => 'Unpublish') %>
			<%= f.submit(:class => 'button medium green', :value => 'Update page') %>
		<% end %>
  </div>
<% end %>

app/views/pages/_page.html.erb
<% page ||= @page %>

<article class="<%= "unpublished" unless page.published? || !highlight_unpublished %>">
	<% unless page.published? || !highlight_unpublished %>
		<span class='warning'>
				Unpublished 
				<%= link_to 'Edit', edit_page_path(page), :class => 'button white medium' %>
		</span>
	<% end %>
	
	<% unless root? %><header><%= page.title %></header><% end %>
	
	<div><%= markdown(page.content) %></div>
  
	<%= render :partial => "pages/page_controls" if show_nav && admin? %>

</article>

app/views/pages/_page_controls.html.erb
<% page ||= @page %>

<div class='controls'>	
	<%= link_to '&larr;	Back'.html_safe, root_url, :class => 'button white medium left' unless root?  %>
	<%= link_to 'Edit', edit_page_path(page), :class => 'button orange medium' %>
</div>

app/views/pages/edit.html.erb
<section>
	<header>Editing page</header>

	<%= render 'form' %>

</section>

app/views/pages/new.html.erb
<section>
	<header>New page</header>

	<%= render 'form' %>

</section>

app/views/pages/show.html.erb
<% body_classes << 'pages' %>
<% content_for :title do %>
	<%= "#{@page.title} | " unless root? %>
<% end %>

<section>
	<%= render :partial => @page, :locals => {:show_nav => true, :highlight_unpublished => false} %>
	<%= render :partial => 'events/upcoming' if Settings.get("events:enabled?") && Settings.get("events:show_upcoming_events") && root?  %>
	<%= render :partial => 'posts/recent' if Settings.get("blog:enabled?") && Settings.get("blog:show_recent_posts") && root?  %>
</section>