config/routes.rb
Bloodycms::Application.routes.draw do
  resources :sponsors, :path => Settings.get("sponsors:path", "sponsors") if Settings.get('sponsors:enabled?')
  match "/sponsors/image/:size/:id.png" => "sponsors#image" if Settings.get('sponsors:enabled?')
  resources :events,  :path => Settings.get("events:path", "events") if Settings.get('events:enabled?')
  resources :posts, :path => Settings.get("blog:path", "blog") if Settings.get('blog:enabled?')
  resources :pages, :except => :index
  resources :authentications
  resources :admins
  
  match "/options" => "options#index", :as => "options"  
  
  #authentication
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/twitter/setup', :to => 'authentications#setup'
  match '/auth/failure' => redirect("/")
  match '/login' => redirect('/auth/twitter'), :as => "login"
  match '/logout' => "authentications#destroy", :as => "logout"
  
  
  #pages to root domain
  match "/:id" => "pages#show", :as => "root_page", :method => :get

  #the root url can be configured
  root :to => 'frontpage#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user, :logged_in?, :admin?
  before_filter :current_user, :logged_in?, :admin?, :ensure_installed, :ensure_one_admin
  
  private 
  
  def require_login 
    unless logged_in?
      cookies[:auth_token] = request.url unless request.xhr?
      redirect_to login_url
    end
  end
  
  def require_admin
    require_login unless logged_in?
    redirect_to root_url, :alert => "You need to be an admin to get access to this feature" unless admin? || !logged_in?
  end
  
  def current_user
    @current_user ||= load_current_user
  end
  
  def logged_in?
    @logged_in = !@current_user.nil?
  end
  
  def admin?
    @admin = logged_in? && @current_user.is_admin
  end
  
  def ensure_installed
    redirect_to "/options" unless Settings.get("installed?") 
  end
  
  def ensure_one_admin
    redirect_to "/auth/twitter" if User.count.zero? && Settings.get("installed?") 
  end
  
  def load_current_user
    if cookies[:auth_token]
      begin
        return User.find_by_auth_token(cookies[:auth_token])
      rescue
        return nil
      end
    else
      return nil
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def body_classes
    @body_classes ||= [controller.controller_name]
  end
  
  def markdown(text)
    options = [:hard_wrap, :autolink, :no_intraemphasis, :fenced_code, :gh_blockcode]
    text = syntax_highlighter(Redcarpet.new(text, *options).to_html)
    parse_shortcodes(text).html_safe
  end
  
  def safe_markdown(text)
    options = [:hard_wrap, :filter_html, :autolink, :no_intraemphasis, :fenced_code, :gh_blockcode]
    text = syntax_highlighter(Redcarpet.new(text, *options).to_html)
    parse_shortcodes(text).html_safe
  end
  
  def syntax_highlighter(html)
    doc = Nokogiri::HTML(html)
    doc.search("//pre[@lang]").each do |pre|
      pre.replace Albino.colorize(pre.text.rstrip, pre[:lang])
    end
    doc.to_s
  end
  
  def show_sidebar_module?(name)
    self.active_module?(name) && Settings.get("#{name}:in_nav?") 
  end
  
  def active_module?(name)
    Settings.get("#{name}:enabled?")
  end
  
  def active_class_for_path(classname, path)
    return classname if path == request.path
  end
  
  def root?
    request.url == root_url
  end
  
  def map(address)
    address = address.gsub("\n", " ")
    image_url = "http://maps.googleapis.com/maps/api/staticmap?center=#{address}&markers=#{address}&zoom=14&size=400x100&sensor=false"
    link_url = "http://maps.google.co.uk/maps?q=#{address}"
    link_to image_tag(image_url, :class => "map"), link_url, :target => "_blank"
  end
  
  def eventbrite_tickets(id) 
    "<iframe  src='http://www.eventbrite.com/tickets-external?eid=#{id}&ref=etckt' frameborder='0' height='300px' width='100%' vspace='0' hspace='0' marginheight='5' marginwidth='5' scrolling='auto' allowtransparency='true' id='eventbriteframe'></iframe>".html_safe
  end
  
  def parse_shortcodes(text)
    text.sub(/\[tickets=(.+)\]/) do
      if event = Event.find_by_slug($1)
        eventbrite_tickets(event.eventbrite_id) if event.eventbrite_id
      end
    end
  end
end

app/views/application/_controls_header.html.erb
<nav id='controls'>
	<ul>
		<li>
			<%= image_tag(current_user.image, :width => 20, :class => 'avatar') if logged_in? %>
			<%= " Logged in as #{current_user.name}" if logged_in?  %>&nbsp;&nbsp;
			<%= link_to 'New page', new_page_path, :class => 'button green medium' if active_module?('pages') && admin?  %>
			<%= link_to 'New post', new_post_path, :class => 'button blue medium' if active_module?('blog') && admin?  %>
			<%= link_to 'New event', new_event_path, :class => 'button gray medium' if active_module?('events') && admin?  %>
			<%= link_to "Logout &rarr; ".html_safe, "/logout", :class => "button medium white" if logged_in? %>
			<%= link_to image_tag("twitter_connect.gif"), "/login" if !logged_in? && Settings.get("installed?") %>	
		</li>
	</ul>
</nav>

app/views/application/_flash_messages.html.erb
<% if flash[:alert] || flash[:notice] %>
  <div id="notice" <% if flash[:alert] %>class="warning"<% end %>>
    <span><%= flash[:alert] || flash[:notice] %></span>
  </div>
<% end %>

app/views/application/_footer.html.erb
<footer>
		Powered by <a href='https://bloodysoftware.com/cms'>Bloody CMS</a>
		<%= "|" if Settings.get("footer:text")  %>
		<%= markdown(Settings.get("footer:text")) if Settings.get("footer:text")   %>
</footer>

app/views/application/_header.html.erb
<header>
	<%= link_to image_tag(Settings.get("header_image", "bloody_cms.png"), :class => 'header'), root_url %>
</header>

app/views/application/_markdown_info.html.erb
<span class='info'>
	<a href='http://daringfireball.net/projects/markdown/basics' target='_blank'>Markup your text with Markdown.</a>
	We already enabled auto-linking and syntax highlighting.
</span>

app/views/application/_navigation.html.erb
<aside>
	<% if !Settings.get("installed?") %>
		<%= link_to "installer" , "installer#index", :class => 'active'  %>
	<% else %>
		<% class_name = root? ? 'active' : '' %>
		<%= link_to Settings.get("home:sidebar_title", "home") , root_url, :class => class_name if Settings.get('home:enabled?') %>
	
		<% class_name = params[:controller] == "posts" && class_name.blank? ? 'active' : '' %>
		<%= link_to Settings.get("blog:sidebar_title"), posts_path, :class => class_name  if show_sidebar_module?('blog') %>


		<% class_name = params[:controller] == "events" && class_name.blank? ? 'active' : '' %>
		<%= link_to Settings.get("events:sidebar_title"), events_path, :class => class_name  if show_sidebar_module?('events') %>


		<% class_name = params[:controller] == "sponsors" && class_name.blank? ? 'active' : '' %>
		<%= link_to Settings.get("sponsors:sidebar_title"), sponsors_path, :class => class_name  if show_sidebar_module?('sponsors') %>


		<% pages = admin? ? Page.order("sidebar_title ASC") : Page.published.in_sidebar.order("sidebar_title ASC") %>
		<%= render :partial => 'navigation_pages', :locals => {:pages => pages} if show_sidebar_module?('pages') %>		
		
		<%= link_to 'rss', posts_path(:rss), :class => "rss"  if active_module?('blog') && Settings.get("blog:rss_in_sidebar?") %>
		<%= link_to "#{Settings.get("events:sidebar_title")} rss", events_path(:rss), :class => "rss"  if active_module?('events') && Settings.get("events:rss_in_sidebar?") %>
		
		
		<% if admin? %>
			<hr/>
			<%= link_to "configuration", options_path, :class => active_class_for_path("active", options_path) %>
			<%= link_to "administrators", admins_path, :class => active_class_for_path("active", admins_path) %>
		<% end %>
	<% end %>
</aside>

app/views/application/_navigation_pages.html.erb
<% pages.each do |page| %>
	<% class_name = params[:controller] == 'pages' && params[:id] == page.slug ? 'active' : '' %>
	<% 
		appendix = ""
		appendix += "<span>draft |</span> " if !page.published?
		appendix += " <span>hidden |</span> " if page.hidden? %>
	<%= link_to (appendix.html_safe+"#{page.sidebar_title_or_title}").html_safe, root_page_path(page), :class => class_name  %>
<% end %>

app/views/application/_sponsors.html.erb
<aside class='sponsors'>
	<%= link_to Settings::get("sponsors:sidebar_title") , sponsors_path, :class => 'title' %>
	<% Sponsor.all.shuffle.each do |sponsor| %>
		<%= link_to image_tag(sponsor.image_for_size("200x200")), sponsor.url, :class => 'sponsor' %>
	<% end %>
</aside>