config/routes.rb
Bloodycms::Application.routes.draw do
  resources :sponsors, :path => Settings.get("sponsors:path", "sponsors") if Settings.get('sponsors:enabled?')
  match "/sponsors/image/:size/:id.png" => "sponsors#image" if Settings.get('sponsors:enabled?')
  resources :events,  :path => Settings.get("events:path", "events") if Settings.get('events:enabled?')
  resources :posts, :path => Settings.get("blog:path", "blog") if Settings.get('blog:enabled?')
  resources :pages, :except => :index
  resources :authentications
  resources :admins
  
  match "/options" => "options#index", :as => "options"  
  
  #authentication
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/twitter/setup', :to => 'authentications#setup'
  match '/auth/failure' => redirect("/")
  match '/login' => redirect('/auth/twitter'), :as => "login"
  match '/logout' => "authentications#destroy", :as => "logout"
  
  
  #pages to root domain
  match "/:id" => "pages#show", :as => "root_page", :method => :get

  #the root url can be configured
  root :to => 'frontpage#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %><%= Settings.get('title', 'Bloody CMS') %></title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
  <%= javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js" %>
	<%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" %>
	<%= javascript_include_tag "jquery.ui.datetimepicker.min.js" %>
	<%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/smoothness/jquery-ui.css" %>
	<%= content_tag :link, nil, :rel => 'alternate', :type => 'application/rss+xm', :title => "#{Settings.get('blog:title')} RSS", :href => posts_url(:rss) if Settings.get('blog:enabled?') %>
	<%= content_tag :link, nil, :rel => 'alternate', :type => 'application/rss+xm', :title => "#{Settings.get('events:title')} RSS", :href => events_url(:rss) if Settings.get('events:enabled?') %>
</head>
<body class="<%= body_classes.join(' ') %>">
	
<%= render :partial => 'controls_header' %>
<%= render :partial => 'header' %>
<%= render :partial => 'flash_messages' %>
<%= render :partial => 'navigation' %>
<%= render :partial => 'sponsors' if Settings.get('sponsors:enabled?') %>

<%= yield %>
<%= render :partial => 'footer' %>


</body>
</html>